<?php

namespace Database\Seeders;

use App\Models\HomeSection;
use App\Models\Job;
use App\Models\SiteSetting;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // 1. Seed Admin Users
        User::updateOrCreate(
            ['email' => 'admin@bfconsultancy.in'],
            [
                'name' => 'Bright Future Admin',
                'password' => Hash::make('password123'),
                'email_verified_at' => now(),
            ]
        );

        User::updateOrCreate(
            ['email' => 'admin@brightfuture.com'],
            [
                'name' => 'Bright Future Admin',
                'password' => Hash::make('admin123'),
                'email_verified_at' => now(),
            ]
        );

        // 2. Seed Site Settings & Logo
        $settings = [
            ['key' => 'site_logo', 'value' => 'assets/images/logo.png', 'group' => 'logo'],
            ['key' => 'site_name', 'value' => 'Bright Future Consultancy', 'group' => 'general'],
            ['key' => 'site_tagline', 'value' => 'HR & Educational Consulting Agency in West Bengal', 'group' => 'general'],
            ['key' => 'contact_phone', 'value' => '+91 7001420469', 'group' => 'contact'],
            ['key' => 'contact_email', 'value' => 'brightfutureconsultancybwn@gmail.com', 'group' => 'contact'],
            ['key' => 'whatsapp_number', 'value' => '7001420469', 'group' => 'contact'],
            ['key' => 'address', 'value' => 'Golapbagh, Barddhaman, West Bengal, India', 'group' => 'contact'],
            ['key' => 'footer_about', 'value' => 'Bright Future Consultancy is a premier HR and educational consulting agency based in West Bengal, specializing in providing comprehensive job updates and career guidance across a variety of sectors.', 'group' => 'general'],
        ];

        foreach ($settings as $setting) {
            SiteSetting::updateOrCreate(['key' => $setting['key']], $setting);
        }

        // 3. Seed Dynamic Home Page Sections
        $sections = [
            [
                'section_key' => 'hero',
                'section_name' => 'Section 01: Hero Banner',
                'tagline' => 'WELCOME TO BRIGHT FUTURE CONSULTANCY',
                'title' => 'Building Futures, Empowering Careers',
                'subtitle' => 'Your Trusted HR & Educational Placement Partner in West Bengal & Pan India',
                'description' => 'We help jobseekers secure 100% genuine, free placement opportunities across Airlines, IT, Overseas, Back Office, and Industrial sectors.',
                'button_text' => 'Explore All Jobs',
                'button_url' => '/jobs',
                'image_path' => 'assets/images/hero-banner.png',
                'is_visible' => true,
                'sort_order' => 1,
            ],
            [
                'section_key' => 'our_story',
                'section_name' => 'Section 02: Our Story & Leadership',
                'tagline' => 'ABOUT US',
                'title' => 'OUR STORY',
                'subtitle' => 'Empowering Job Seekers Across West Bengal & Beyond',
                'description' => 'Bright Future Consultancy is a premier HR and educational consulting agency based in West Bengal, specializing in providing comprehensive job updates and career guidance across a variety of sectors. With a firm commitment to helping jobseekers secure their ideal positions, we offer tailored solutions and expert advice to meet the evolving needs of both individuals and businesses.',
                'button_text' => 'Read more about us',
                'button_url' => '/about.html',
                'image_path' => 'assets/images/team/manirul.svg',
                'content_json' => [
                    'leader_name' => 'Mohammad Manirul',
                    'leader_role' => 'Founder & CEO',
                    'leader_bio' => 'Visionary founder dedicated to transparent placement services and student career transformation across West Bengal.',
                ],
                'is_visible' => true,
                'sort_order' => 2,
            ],
            [
                'section_key' => 'sectors',
                'section_name' => 'Section 03: Manpower Sectors',
                'tagline' => 'SECTORS WE COVER',
                'title' => 'We Provide Manpower for those Sectors',
                'subtitle' => 'Browse our wide range of placement categories',
                'description' => 'From Aviation to Overseas engineering, we bridge top talent with trusted employers nationwide.',
                'button_text' => 'View All Sectors',
                'button_url' => '/categories.html',
                'is_visible' => true,
                'sort_order' => 3,
            ],
            [
                'section_key' => 'placements',
                'section_name' => 'Section 04: Placement Success Stories',
                'tagline' => 'SUCCESS STORIES',
                'title' => 'Successful Joining Candidates',
                'subtitle' => 'Candidates placed in top companies',
                'description' => 'Our "Success Stories" proudly displays messages from happy clients and successful job-seekers highlighting their experience with Bright Future.',
                'button_text' => 'Join Us Today',
                'button_url' => '/join.html',
                'content_json' => [
                    [
                        'name' => 'Hafijur Mondal',
                        'sector' => 'Airlines Ground Staff',
                        'company' => 'IndiGo Airlines',
                        'testimonial' => 'Got selected as ground staff at Kolkata Airport without paying any fake agent fees. Thank you Bright Future!',
                        'joining_date' => 'August 2026',
                    ],
                    [
                        'name' => 'Sk Samim',
                        'sector' => 'Back Office Executive',
                        'company' => 'TCS Vendor Partner',
                        'testimonial' => 'The interview guidance and resume building help was outstanding. Very genuine consultancy in Barddhaman.',
                        'joining_date' => 'July 2026',
                    ],
                    [
                        'name' => 'Sahil Sk',
                        'sector' => 'Overseas HVAC Technician',
                        'company' => 'Gulf Placement UAE',
                        'testimonial' => 'Secured free visa and overseas technician job in Dubai. Mohammad sir guided me personally.',
                        'joining_date' => 'June 2026',
                    ],
                ],
                'is_visible' => true,
                'sort_order' => 4,
            ],
            [
                'section_key' => 'faqs',
                'section_name' => 'Section 05: Frequently Asked Questions',
                'tagline' => 'GOT QUESTIONS?',
                'title' => 'How can we help you?',
                'subtitle' => 'Clear answers to your recruitment queries',
                'description' => 'Everything you need to know about our free job updates, candidate registration, and placement process.',
                'content_json' => [
                    ['q' => 'Are all jobs on Bright Future 100% free?', 'a' => 'Yes! We do not charge jobseekers any registration fees for genuine placement opportunities.'],
                    ['q' => 'How do I apply for Overseas Jobs?', 'a' => 'Click on View Vacancies in Overseas section or send your resume directly to our official WhatsApp number.'],
                    ['q' => 'Where is your office located?', 'a' => 'Our main office is located in Golapbagh, Barddhaman, West Bengal. Visitors are welcome during working hours.'],
                ],
                'is_visible' => true,
                'sort_order' => 5,
            ],
            [
                'section_key' => 'testimonials',
                'section_name' => 'Section 06: Client & Candidate Feedback',
                'tagline' => 'CLIENT FEEDBACK',
                'title' => 'What do people say about our services?',
                'subtitle' => 'Real reviews from employers and job candidates',
                'description' => 'Hear directly from HR heads and candidates who have benefited from our manpower recruitment agency.',
                'is_visible' => true,
                'sort_order' => 6,
            ],
        ];

        foreach ($sections as $secData) {
            HomeSection::updateOrCreate(['section_key' => $secData['section_key']], $secData);
        }

        // 4. Seed ALL 25 Authentic Job Posts from singlejobs database
        $jobPosts = [
            [
                'title' => 'Job Opening Snapdeal Delivery Partner',
                'slug' => 'job-opening-snapdeal-delivery-partner',
                'company' => 'Snapdeal Logistics Partner • Kolkata, Barddhaman',
                'sector_slug' => 'logistics',
                'sector_name' => 'Driver & Logistics',
                'location' => 'Kolkata, Barddhaman',
                'salary' => '₹ 22,000 / mo',
                'qualification' => '5th / 8th Pass',
                'badge_tag' => '100% FREE JOBS',
                'description' => 'Snapdeal logistics partner is hiring delivery partners and drivers for daily parcel delivery routes in Barddhaman town and surrounding Kolkata areas.',
                'duties' => 'Pick up delivery parcels from logistics hub, route planning, timely doorstep delivery, and cash-on-delivery handling.',
                'requirements' => 'Candidates with 5th, 8th or 10th pass qualification are welcome. Driving license or Commercial Badge preferred.',
                'benefits' => '₹22,000 monthly fixed salary + fuel allowance + performance incentives + ESIC medical coverage.',
                'contact_email' => 'brightfutureconsultancybwn@gmail.com',
                'contact_phone' => '+91 7001420469',
                'poster_image' => 'assets/images/posters/snapdeal_poster.svg',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'title' => 'REGISTRATION FORM FOR ALL JOBS',
                'slug' => 'registration-form-for-all-jobs',
                'company' => 'Bright Future Consultancy • All Over West Bengal',
                'sector_slug' => 'all-india',
                'sector_name' => 'Pan-India Vacancies',
                'location' => 'All Over West Bengal',
                'salary' => '₹ 12,000 TO 35,000',
                'qualification' => '10th / 12th / Graduate Pass',
                'badge_tag' => 'FREE REGISTRATION',
                'description' => 'One-time candidate registration for multiple job openings across 50+ corporate partner companies in Barddhaman, Kolkata, Durgapur and Howrah.',
                'duties' => 'Back Office Assistant, Data Entry Operator, Retail Sales Executive, Supermarket Helper, Security Guard & Field Executive.',
                'requirements' => 'Freshers & experienced 10th, 12th pass & Graduates.',
                'benefits' => 'Submit your details once to receive direct call-letter updates for verified interview drives.',
                'contact_email' => 'brightfutureconsultancybwn@gmail.com',
                'contact_phone' => '+91 7001420469',
                'poster_image' => 'assets/images/posters/registration_poster.svg',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'title' => 'STORE ASSISTANT (More Supermarket)',
                'slug' => 'store-assistant-more-supermarket',
                'company' => 'More Supermarket Retail • Purba Barddhaman',
                'sector_slug' => 'supermarket',
                'sector_name' => 'Supermarket & Retail',
                'location' => 'Purba Barddhaman',
                'salary' => '₹ 15,000 / mo',
                'qualification' => 'Full Time & Part Time',
                'badge_tag' => 'RETAIL JOB',
                'description' => 'More Supermarket retail chain is hiring store assistants, counter cashiers, and inventory helpers for their Barddhaman store branch.',
                'duties' => 'Customer assistance, billing counter management, grocery stock shelf stacking, barcode scanning.',
                'requirements' => '10th / 12th pass or freshers with good interpersonal skills.',
                'benefits' => '₹15,000 fixed salary on direct company payroll with overtime allowance.',
                'contact_email' => 'brightfutureconsultancybwn@gmail.com',
                'contact_phone' => '+91 7001420469',
                'poster_image' => 'assets/images/posters/supermarket_poster.svg',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 3,
            ],
            [
                'title' => 'ATM Cash Refilling Officer',
                'slug' => 'atm-cash-refilling-officer',
                'company' => 'CMS Banking Security • Barddhaman, Kolkata',
                'sector_slug' => 'banking',
                'sector_name' => 'Banking & Security',
                'location' => 'Barddhaman, Kolkata',
                'salary' => '₹ 18,000 / mo',
                'qualification' => '10th / 12th Pass',
                'badge_tag' => 'BANKING JOB',
                'description' => 'Urgent hiring for ATM Cash Custodians and Refilling Officers across private bank ATM routes in Purba Barddhaman and Bankura.',
                'duties' => 'Vault cash loading into bank ATMs, ATM cassette auditing, and cash logistics management.',
                'requirements' => 'Clean background verification, 10th or 12th pass.',
                'benefits' => 'Direct joining on company payroll with PF, ESIC & insurance benefits.',
                'contact_email' => 'brightfutureconsultancybwn@gmail.com',
                'contact_phone' => '+91 7001420469',
                'poster_image' => 'assets/images/posters/atm_poster.svg',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 4,
            ],
            [
                'title' => 'Pharmacy Assistant / Trainee / Pharmacist',
                'slug' => 'pharmacy-assistant-trainee-pharmacist',
                'company' => 'Apollo Pharmacies Limited • Purba Barddhaman',
                'sector_slug' => 'pharmacy',
                'sector_name' => 'Pharmacy Sector',
                'location' => 'Purba Barddhaman',
                'salary' => '₹ 15,000 - ₹ 20,000',
                'qualification' => 'D.Pharm / B.Pharm / 10th+',
                'badge_tag' => 'PHARMA JOB',
                'description' => 'Apollo Pharmacies Limited is conducting urgent spot interviews for pharmacy assistants, trainees, and registered pharmacists.',
                'duties' => 'Prescription medicine dispensing, inventory stock checking, billing counter management.',
                'requirements' => 'D.Pharm, B.Pharm, or 10th/12th pass with medical store experience.',
                'benefits' => 'Direct company payroll, medicine employee discounts, PF and ESI.',
                'contact_email' => 'brightfutureconsultancybwn@gmail.com',
                'contact_phone' => '+91 7001420469',
                'poster_image' => 'assets/images/posters/apollo_poster.svg',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 5,
            ],
            [
                'title' => 'Escort Guard / Railway Goods Guard',
                'slug' => 'escort-guard-railway-goods-guard',
                'company' => 'Escort Security & Logistics • Barddhaman & Asansol',
                'sector_slug' => 'security',
                'sector_name' => 'Security & Railway',
                'location' => 'Barddhaman & Asansol',
                'salary' => '₹ 18,000 / mo',
                'qualification' => '8th / 10th / 12th Pass',
                'badge_tag' => 'COMPANY PAYROLL',
                'description' => 'Direct spot hiring for cargo train escort guards and industrial goods transport security guards.',
                'duties' => 'Goods escorting, safety inspection, depot monitoring, cargo security.',
                'requirements' => 'Physical fitness, valid ID proof, 8th or 10th pass.',
                'benefits' => 'Free fooding & lodging provided by company. Spot joining letter on interview day.',
                'contact_email' => 'brightfutureconsultancybwn@gmail.com',
                'contact_phone' => '+91 7001420469',
                'poster_image' => 'assets/images/posters/escort_poster.svg',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 6,
            ],
            [
                'title' => 'ALL OVERSEAS JOBS (Gulf & Europe Placement)',
                'slug' => 'all-overseas-jobs-gulf-europe-placement',
                'company' => 'Overseas Recruitment Partners • UAE & Qatar',
                'sector_slug' => 'overseas',
                'sector_name' => 'Overseas Vacancy',
                'location' => 'UAE, Qatar & Europe',
                'salary' => '₹ 45,000 – ₹ 90,000',
                'qualification' => 'ITI / Diploma / Experienced',
                'badge_tag' => '100% FREE PLACEMENT',
                'description' => 'Overseas job vacancies for technicians, electricians, drivers, and hotel staff in UAE, Qatar, Saudi Arabia & Europe. Free visa processing assistance.',
                'duties' => 'Technical maintenance, site operations, panel assembly, or hospitality duties as per Gulf standard procedures.',
                'requirements' => "1. Valid Indian Passport with minimum 2 years validity.\n2. Relevant ITI, Diploma, or Trade Test certificate.\n3. Minimum 2+ years experience in technical trade or hospitality.",
                'benefits' => "• Free Employment Visa & Air Ticket\n• Free Shared Accommodation & Food Allowance\n• Medical Insurance & Overtime Compensation",
                'contact_email' => 'brightfutureconsultancybwn@gmail.com',
                'contact_phone' => '+91 7001420469',
                'poster_image' => 'assets/images/roles/overseas_jobs.svg',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 7,
            ],
            [
                'title' => 'ALL JOBS VACANCY UNDER NAPS (Govt Apprenticeship)',
                'slug' => 'all-jobs-vacancy-under-naps',
                'company' => 'NAPS Govt Scheme • West Bengal Industries',
                'sector_slug' => 'naps',
                'sector_name' => 'Govt Apprenticeship',
                'location' => 'West Bengal Industries',
                'salary' => '₹ 12,000 - ₹ 18,000',
                'qualification' => '10th / 12th / ITI Pass',
                'badge_tag' => 'GOVT APPRENTICESHIP',
                'description' => 'Govt. National Apprenticeship Promotion Scheme (NAPS) vacancies with stipend, official NAPS certificate & direct company absorption.',
                'duties' => 'Industrial on-job training, assembly operations, machine operation under master trainers.',
                'requirements' => '10th, 12th or ITI pass under 28 years of age.',
                'benefits' => 'Govt certificate, direct monthly stipend, corporate absorption opportunity.',
                'contact_email' => 'brightfutureconsultancybwn@gmail.com',
                'contact_phone' => '+91 7001420469',
                'poster_image' => 'assets/images/roles/naps_jobs.svg',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 8,
            ],
            [
                'title' => 'Govt. Contractual Jobs Section',
                'slug' => 'govt-contractual-jobs-section',
                'company' => 'Govt. Departments & Municipalities',
                'sector_slug' => 'govt',
                'sector_name' => 'Govt Contractual',
                'location' => 'West Bengal State Offices',
                'salary' => '₹ 16,000 - ₹ 28,000',
                'qualification' => '8th / 10th / 12th / Graduate',
                'badge_tag' => 'GOVT CONTRACTUAL',
                'description' => 'Govt. contractual staff, computer operator, and office helper posts across West Bengal state government offices.',
                'duties' => 'File management, public counter support, data entry in government portals.',
                'requirements' => 'Clean background verification, Bengali/Hindi reading and writing fluency.',
                'benefits' => 'Fixed monthly salary, government gazetted holidays, experience credentials.',
                'contact_email' => 'brightfutureconsultancybwn@gmail.com',
                'contact_phone' => '+91 7001420469',
                'poster_image' => 'assets/images/roles/govt_contractual.svg',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 9,
            ],
            [
                'title' => 'AIRLINES SECTOR JOBS (Ground Staff & Cabin Crew)',
                'slug' => 'airlines-sector-jobs-ground-staff',
                'company' => 'IndiGo & Aviation Partners • Kolkata Airport',
                'sector_slug' => 'airlines',
                'sector_name' => 'Airlines Sector',
                'location' => 'Kolkata International Airport (CCU)',
                'salary' => '₹ 25,000 - ₹ 45,000',
                'qualification' => '12th Pass / Graduate',
                'badge_tag' => 'AIRLINES VACANCY',
                'description' => 'Airlines ground staff, customer service agent, and luggage handling positions available at Kolkata International Airport. 100% free placement assistance.',
                'duties' => 'Passenger boarding assistance, baggage check-in desk, terminal security coordination.',
                'requirements' => '12th pass or Graduate, pleasant communication skills, good grooming.',
                'benefits' => 'Airport pass, flight discounts, health insurance, provident fund.',
                'contact_email' => 'brightfutureconsultancybwn@gmail.com',
                'contact_phone' => '+91 7001420469',
                'poster_image' => 'assets/images/roles/airlines_jobs.svg',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 10,
            ],
            [
                'title' => 'Back Office Sector & Data Entry',
                'slug' => 'back-office-sector-data-entry',
                'company' => 'Corporate IT & Finance Firms',
                'sector_slug' => 'backoffice',
                'sector_name' => 'Back Office Sector',
                'location' => 'Barddhaman & Kolkata',
                'salary' => '₹ 14,000 - ₹ 24,000',
                'qualification' => '12th Pass / Graduate',
                'badge_tag' => 'OFFICE JOB',
                'description' => 'Back office executive, MS Excel operator, telecaller, and document verifier positions in Barddhaman & Kolkata.',
                'duties' => 'Data entry in ERP software, client KYC verification, monthly report compilation.',
                'requirements' => 'Basic computer knowledge and typing speed of 25+ wpm.',
                'benefits' => 'Fixed working hours, Sundays off, performance bonuses.',
                'contact_email' => 'brightfutureconsultancybwn@gmail.com',
                'contact_phone' => '+91 7001420469',
                'poster_image' => 'assets/images/roles/backoffice_jobs.svg',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 11,
            ],
            [
                'title' => 'Hospitality & Hotel Jobs Section',
                'slug' => 'hospitality-hotel-jobs-section',
                'company' => 'Luxury Hotels & Resort Partners',
                'sector_slug' => 'hospitality',
                'sector_name' => 'Hospitality & Hotel',
                'location' => 'Barddhaman, Durgapur & Kolkata',
                'salary' => '₹ 15,000 - ₹ 28,000',
                'qualification' => '10th / 12th / Hotel Mgmt',
                'badge_tag' => 'HOTEL JOBS',
                'description' => 'Front desk reception, steward, chef assistant, and housekeeping posts in Barddhaman & Durgapur hotels.',
                'duties' => 'Guest welcoming, room service management, food & beverage coordination.',
                'requirements' => 'Polite demeanor, communication skills, diploma in hotel management preferred.',
                'benefits' => 'Duty meals provided, room accommodation, tips and service charges.',
                'contact_email' => 'brightfutureconsultancybwn@gmail.com',
                'contact_phone' => '+91 7001420469',
                'poster_image' => 'assets/images/roles/hospitality_hotel.svg',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 12,
            ],
            [
                'title' => 'Automobile Sector (Tata Motors & Suzuki)',
                'slug' => 'automobile-sector-tata-motors-suzuki',
                'company' => 'Tata Motors & Maruti Suzuki Plants',
                'sector_slug' => 'auto',
                'sector_name' => 'Automobile Sector',
                'location' => 'Industrial Plants, West Bengal & Gujarat',
                'salary' => '₹ 16,000 - ₹ 26,000',
                'qualification' => '10th / ITI Fitter / Electrician',
                'badge_tag' => 'AUTO INDUSTRY',
                'description' => 'Assembly line technician, fitter, auto electrician, and quality checker jobs in automobile manufacturing units.',
                'duties' => 'Component assembly, mechanical inspection, torque testing, line troubleshooting.',
                'requirements' => 'ITI (Fitter / Electrician / Motor Mechanic) or 10th pass with technical inclination.',
                'benefits' => 'Subsidized canteen food, uniform, bus transport, overtime allowances.',
                'contact_email' => 'brightfutureconsultancybwn@gmail.com',
                'contact_phone' => '+91 7001420469',
                'poster_image' => 'assets/images/roles/automobile_jobs.svg',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 13,
            ],
            [
                'title' => 'Medical Sector & Hospital Staff',
                'slug' => 'medical-sector-hospital-staff',
                'company' => 'Private Hospitals & Diagnostics',
                'sector_slug' => 'medical',
                'sector_name' => 'Medical & Healthcare',
                'location' => 'Barddhaman & Kolkata Hospitals',
                'salary' => '₹ 15,000 - ₹ 30,000',
                'qualification' => 'Nursing / GNM / Paramedical',
                'badge_tag' => 'HEALTHCARE',
                'description' => 'Nursing staff, OT technician, lab assistant, and hospital receptionist vacancies in top healthcare facilities.',
                'duties' => 'Patient vital signs check, sample collection, hospital ward management, registration counter.',
                'requirements' => 'ANM / GNM Nursing or Paramedical certificate.',
                'benefits' => 'Free medical care for family, shift allowances, permanent absorption.',
                'contact_email' => 'brightfutureconsultancybwn@gmail.com',
                'contact_phone' => '+91 7001420469',
                'poster_image' => 'assets/images/roles/medical_sector.svg',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 14,
            ],
            [
                'title' => 'Banking Sector & Financial Services',
                'slug' => 'banking-sector-financial-services',
                'company' => 'Axis Bank, HDFC & Private Banks',
                'sector_slug' => 'banking',
                'sector_name' => 'Banking & Finance',
                'location' => 'Barddhaman, Asansol & Kolkata',
                'salary' => '₹ 18,000 - ₹ 32,000',
                'qualification' => '12th / Graduate Pass',
                'badge_tag' => 'BANKING CAREER',
                'description' => 'Banking assistant, loan officer, phone banking specialist, and ATM operations executive in Barddhaman branches.',
                'duties' => 'Account opening assistance, gold loan processing, customer queries resolution.',
                'requirements' => 'Graduate in any stream, basic knowledge of banking products.',
                'benefits' => 'Direct payroll or verified vendor payroll, quarterly incentives, career promotions.',
                'contact_email' => 'brightfutureconsultancybwn@gmail.com',
                'contact_phone' => '+91 7001420469',
                'poster_image' => 'assets/images/roles/banking_sector.svg',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 15,
            ],
            [
                'title' => 'AC Mechanic & Refrigeration Technician',
                'slug' => 'ac-mechanic-refrigeration-technician',
                'company' => 'HVAC & Service Partners',
                'sector_slug' => 'technical',
                'sector_name' => 'Technical & HVAC',
                'location' => 'West Bengal & Pan-India Projects',
                'salary' => '₹ 16,000 - ₹ 25,000',
                'qualification' => '10th / ITI RAC Pass',
                'badge_tag' => 'HVAC JOBS',
                'description' => 'AC installation, maintenance technician, compressor repair, and chiller operator jobs across commercial projects.',
                'duties' => 'Split & ductable AC installation, gas charging, copper piping, preventive maintenance.',
                'requirements' => 'ITI RAC certification or 1+ year practical HVAC field experience.',
                'benefits' => 'Tool kit provided, fuel allowance for field travel, overtime payments.',
                'contact_email' => 'brightfutureconsultancybwn@gmail.com',
                'contact_phone' => '+91 7001420469',
                'poster_image' => 'assets/images/roles/ac_mechanic.svg',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 16,
            ],
            [
                'title' => 'AC Coach Attender & Railway Staff',
                'slug' => 'ac-coach-attender-railway-staff',
                'company' => 'Indian Railways Contracting Partner',
                'sector_slug' => 'railway',
                'sector_name' => 'Railway & Transport',
                'location' => 'Express Train Routes (Howrah / Sealdah)',
                'salary' => '₹ 16,500 - ₹ 24,000',
                'qualification' => '8th / 10th / 12th Pass',
                'badge_tag' => 'RAILWAY CONTRACT',
                'description' => 'AC coach bedroll staff, train attendant, and passenger assistance staff on express train routes.',
                'duties' => 'Linen distribution, coach cleanliness check, passenger assistance during journeys.',
                'requirements' => '8th or 10th pass, polite behavior, readiness for long distance travel.',
                'benefits' => 'Free onboard food, railway travel duty pass, monthly fixed salary.',
                'contact_email' => 'brightfutureconsultancybwn@gmail.com',
                'contact_phone' => '+91 7001420469',
                'poster_image' => 'assets/images/roles/ac_coach_attender.svg',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 17,
            ],
            [
                'title' => 'Driver Jobs (Heavy & Commercial Vehicles)',
                'slug' => 'driver-jobs-heavy-commercial-vehicles',
                'company' => 'Logistics & Commercial Fleet Partners',
                'sector_slug' => 'driver',
                'sector_name' => 'Driver & Logistics',
                'location' => 'Barddhaman & Kolkata Routes',
                'salary' => '₹ 18,000 - ₹ 28,000',
                'qualification' => 'Valid DL / Badge',
                'badge_tag' => 'COMMERCIAL DRIVER',
                'description' => 'Commercial vehicle driver, delivery truck driver, personal driver, and ambulance driver posts in Barddhaman.',
                'duties' => 'Safe driving, daily vehicle maintenance check, route delivery tracking.',
                'requirements' => 'Valid LMV or HMV Driving License with minimum 1 year driving history.',
                'benefits' => 'Daily trip allowances, vehicle insurance, bonus on zero-accident record.',
                'contact_email' => 'brightfutureconsultancybwn@gmail.com',
                'contact_phone' => '+91 7001420469',
                'poster_image' => 'assets/images/roles/driver_jobs.svg',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 18,
            ],
            [
                'title' => 'Security Guard & Guarding Forces',
                'slug' => 'security-guard-guarding-forces',
                'company' => 'SIS Security & Private Agencies',
                'sector_slug' => 'security',
                'sector_name' => 'Security Forces',
                'location' => 'Banks, Malls & Industrial Plants',
                'salary' => '₹ 14,000 - ₹ 22,000',
                'qualification' => '8th / 10th Pass',
                'badge_tag' => 'SECURITY FORCES',
                'description' => 'Bank security guard, ATM supervisor, industrial site guard, and residential security staff positions.',
                'duties' => 'Access control gate monitoring, visitor log register maintenance, premises patrolling.',
                'requirements' => 'Minimum height 5ft 6in, 8th or 10th pass, physically fit.',
                'benefits' => 'Free accommodation provided, 8/12 hour shift options, PF and ESIC.',
                'contact_email' => 'brightfutureconsultancybwn@gmail.com',
                'contact_phone' => '+91 7001420469',
                'poster_image' => 'assets/images/roles/security_guard.svg',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 19,
            ],
            [
                'title' => 'Call Centre & BPO Customer Support',
                'slug' => 'call-centre-bpo-customer-support',
                'company' => 'TCS Partner & BPO Centers',
                'sector_slug' => 'bpo',
                'sector_name' => 'Call Centre & BPO',
                'location' => 'Kolkata & Salt Lake Sector V',
                'salary' => '₹ 14,000 - ₹ 22,000',
                'qualification' => '10th / 12th Pass',
                'badge_tag' => 'BPO / VOICE',
                'description' => 'Inbound customer service, tele-calling, voice process, and chat support openings in Bengali, Hindi & English.',
                'duties' => 'Inbound calls answering, customer problem resolution, CRM system notes entry.',
                'requirements' => 'Clear speech and polite tone in Bengali or Hindi. Basic English comprehension.',
                'benefits' => 'Cab drop facility for night shifts, monthly sales incentives, cafeteria benefits.',
                'contact_email' => 'brightfutureconsultancybwn@gmail.com',
                'contact_phone' => '+91 7001420469',
                'poster_image' => 'assets/images/roles/call_centre.svg',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 20,
            ],
            [
                'title' => 'Housekeeping Staff & Facility Helpers',
                'slug' => 'housekeeping-staff-facility-helpers',
                'company' => 'Facility Management Agencies',
                'sector_slug' => 'facility',
                'sector_name' => 'Facility & Housekeeping',
                'location' => 'Offices, Malls & Hospitals',
                'salary' => '₹ 12,000 - ₹ 18,000',
                'qualification' => '5th / 8th Pass',
                'badge_tag' => 'FACILITY STAFF',
                'description' => 'Corporate office cleaner, mall housekeeping staff, hospital sanitation staff, and pantry helper vacancies.',
                'duties' => 'Premises sanitization, office desk dusting, restroom cleaning, pantry tea/coffee service.',
                'requirements' => 'Disciplined, hardworking, 5th or 8th pass.',
                'benefits' => 'Uniform provided, paid weekly off, festival bonus.',
                'contact_email' => 'brightfutureconsultancybwn@gmail.com',
                'contact_phone' => '+91 7001420469',
                'poster_image' => 'assets/images/roles/housekeeping_stuff.svg',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 21,
            ],
            [
                'title' => 'Warehouse Executive & Logistics Picker',
                'slug' => 'warehouse-executive-logistics-picker',
                'company' => 'Flipkart & E-Commerce Hubs',
                'sector_slug' => 'logistics',
                'sector_name' => 'Warehouse & Logistics',
                'location' => 'Dankuni & Uluberia Hubs',
                'salary' => '₹ 15,000 - ₹ 23,000',
                'qualification' => '10th / 12th Pass',
                'badge_tag' => 'E-COMMERCE HUB',
                'description' => 'Warehouse picker, package scanner, loader, inventory supervisor, and dispatch officer jobs at logistics hubs.',
                'duties' => 'Handheld barcode scanning, product bin sorting, order cart packing, dispatch truck loading.',
                'requirements' => '10th pass, basic smartphone literacy, active physical stamina.',
                'benefits' => 'Company bus pick up and drop, attendance bonus up to ₹3,000, subsidized meal.',
                'contact_email' => 'brightfutureconsultancybwn@gmail.com',
                'contact_phone' => '+91 7001420469',
                'poster_image' => 'assets/images/roles/warehouse_executive.svg',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 22,
            ],
            [
                'title' => 'IT & Hardware Networking Technician',
                'slug' => 'it-hardware-networking-technician',
                'company' => 'Hardware Support & Tech Firms',
                'sector_slug' => 'it',
                'sector_name' => 'IT & Technology',
                'location' => 'Barddhaman & Kolkata',
                'salary' => '₹ 16,000 - ₹ 26,000',
                'qualification' => '12th / ITI / Diploma Hardware',
                'badge_tag' => 'IT & HARDWARE',
                'description' => 'Desktop support engineer, CCTV technician, printer repair specialist, and computer hardware technician posts.',
                'duties' => 'Windows OS installation, LAN networking cable crimping, CCTV DVR setup, printer servicing.',
                'requirements' => 'Diploma or course in Computer Hardware and Networking, or 1+ year practical bench experience.',
                'benefits' => 'Travel allowance, mobile phone reimbursement, corporate certification support.',
                'contact_email' => 'brightfutureconsultancybwn@gmail.com',
                'contact_phone' => '+91 7001420469',
                'poster_image' => 'assets/images/roles/it_hardware.svg',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 23,
            ],
            [
                'title' => 'Labour & General Factory Helper',
                'slug' => 'labour-general-factory-helper',
                'company' => 'Manufacturing Plants & Warehouses',
                'sector_slug' => 'industrial',
                'sector_name' => 'Industrial & Manufacturing',
                'location' => 'Durgapur & Asansol Industrial Belt',
                'salary' => '₹ 12,000 - ₹ 17,500',
                'qualification' => '5th / 8th Pass',
                'badge_tag' => 'FACTORY HELPER',
                'description' => 'Factory helper, industrial packer, loading assistant, and general labour vacancies with free room lodging.',
                'duties' => 'Material handling, production belt packing, warehouse carton movement.',
                'requirements' => 'Good health and physical strength, 5th pass onwards.',
                'benefits' => 'Free room stay provided on factory premises, overtime at 1.5x rate.',
                'contact_email' => 'brightfutureconsultancybwn@gmail.com',
                'contact_phone' => '+91 7001420469',
                'poster_image' => 'assets/images/roles/labour_helper.svg',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 24,
            ],
            [
                'title' => 'All New and Update Jobs Section',
                'slug' => 'all-new-and-update-jobs-section',
                'company' => 'Bright Future Hiring Partners • West Bengal',
                'sector_slug' => 'all',
                'sector_name' => 'All Sectors',
                'location' => 'Barrackpore & All West Bengal',
                'salary' => '₹ 12,000 - ₹ 35,000',
                'qualification' => '10th / 12th / Graduate Pass',
                'badge_tag' => '100% FREE JOBS',
                'description' => 'Comprehensive listing of fresh job updates across IT, Banking, Retail, Logistics, Healthcare, and Govt. Contractual sectors in West Bengal.',
                'duties' => 'Multiple roles across customer service, back office, field marketing, and technical support.',
                'requirements' => '10th, 12th, or Graduate pass candidates looking for verified placement opportunities.',
                'benefits' => '100% Free Placement, direct interview scheduling, company payroll joining.',
                'contact_email' => 'brightfutureconsultancybwn@gmail.com',
                'contact_phone' => '+91 7001420469',
                'poster_image' => 'assets/images/roles/all_new_jobs.svg',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 25,
            ],
        ];

        foreach ($jobPosts as $post) {
            Job::updateOrCreate(['slug' => $post['slug']], $post);
        }
    }
}
